### ISSUE TITLE
Karibu tests for UI components with Vaadin 14.6+

### ISSUE THREAD

**Issue by fionnachan** [mvysny/karibu-testing#77]
Hello, the project I'm working on was previously on Vaadin 14.5.5 & Karibu v10 1.1.27

I was trying to update Vaadin from 14.5.5 to 14.6.4 / 14.6.5, and then the existing Karibu tests started to break, so I thought to update Karibu to v1.3.0, however it didn't solve the problem.

This is not the full stacktrace, but most of the test failures are due to the same issue:
(For both server-side created components & polymer template components)
For _get()
```
Message:
N/A
Stack trace:
java.lang.NoClassDefFoundError: kotlin/KotlinNothingValueException
	at com.github.mvysny.kaributesting.v10.LocatorKt.find(Locator.kt:193)
	at com.github.mvysny.kaributesting.v10.LocatorKt._find(Locator.kt:139)
	at com.github.mvysny.kaributesting.v10.LocatorKt._get(Locator.kt:107)
	at com.github.mvysny.kaributesting.v10.LocatorJ._get(LocatorJ.java:65)
```

For _click()
```
Message:
N/A
Stack trace:
java.lang.NoClassDefFoundError: kotlin/KotlinNothingValueException
	at com.github.mvysny.kaributesting.v10.LocatorJ._click(LocatorJ.java:94)
	at io.skymind.pathmind.webapp.ui.layouts.components.NotesFieldTest.notesFieldSaveButtonTest(NotesFieldTest.java:44)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
```

In our project, we set up Karibu tests to test the behaviour of the UI components without its attachment to a specific view. It seems like `_get(component)` stopped working with the latest Vaadin & Karibu version.

In our tests, this is the basic setup:
(The following example is a PolymerTemplate component)
The test worked fine before updating Vaadin & Karibu.
```
@Before
public void setUp() {
    MockVaadin.setup(new Routes(), () -> new MockedUI());
    notesField = new NotesField("title", "abc", text -> {}, false, true, false);
}

@After
public void tearDown() {
    MockVaadin.tearDown();
}

@Test
public void notesFieldSaveButtonTest() {
    _click(notesField.save);  // this would result in the error java.lang.NoClassDefFoundError: kotlin/KotlinNothingValueException
}
```

Please let me know if there is anything I can change to fix. If unfortunately Karibu requires a specific view to test the components, we'll have to remove Karibu tests since we already have a comprehensive set of end-to-end tests.

**Comment by mvysny** [comment]
Hi, im on a vacation right now, but the main problem is probably java.lang.NoClassDefFoundError: kotlin/KotlinNothingValueException . Sounds like the kotlin-stdlib jar is missing from the classpath. Please make sure that kotlin 1.5 stdlib is on the classpath

**Comment by satorstefan** [comment]
This did the trick for me:
      <dependency>
        <groupId>org.jetbrains.kotlin</groupId>
        <artifactId>kotlin-stdlib</artifactId>
        <version>1.3.72</version>
      </dependency>

**Comment by fionnachan** [comment]
Thank you @mvysny that was helpful.

**Comment by mvysny** [comment]
No problem, glad that the issue was solved 👍
